hard_tabs                = true
max_width                = 100
newline_style            = "Unix"
reorder_imports          = true
reorder_modules          = true
tab_spaces               = 4
use_field_init_shorthand = true
