[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia node rpc"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-rpc"
repository  = "https://github.com/darwinia-network/darwinia/"
version     = "0.10.0"

[dependencies]
# crates
code           = { package = "parity-scale-codec", version = "2.1.1", default-features = false }
jsonrpc-core   = { version = "15.1.0" }
jsonrpc-pubsub = { version = "15.1.0" }
# darwinia frame
darwinia-balances-rpc   = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "darwinia-v0.11.0" }
darwinia-header-mmr-rpc = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "darwinia-v0.11.0" }
darwinia-staking-rpc    = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "darwinia-v0.11.0" }
dc-db                   = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "darwinia-v0.11.0" }
dc-rpc                  = { features = ["rpc_binary_search_estimate"], git = "https://github.com/darwinia-network/darwinia-common.git", tag = "darwinia-v0.11.0" }
dp-rpc                  = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "darwinia-v0.11.0" }
dvm-ethereum            = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "darwinia-v0.11.0" }
dvm-rpc-runtime-api     = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "darwinia-v0.11.0" }
# darwinia primitives
crab-runtime        = { path = "../runtime/crab" }
darwinia-primitives = { path = "../primitives" }
# substrate client
sc-chain-spec           = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sc-client-api           = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sc-consensus-babe       = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sc-consensus-babe-rpc   = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sc-consensus-epochs     = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sc-finality-grandpa     = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sc-finality-grandpa-rpc = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sc-rpc                  = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sc-sync-state-rpc       = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
# substrate frame
pallet-transaction-payment-rpc = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
substrate-frame-rpc-system     = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
# substrate primitives
sc-network          = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sp-api              = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sp-block-builder    = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sp-blockchain       = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sp-consensus        = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sp-consensus-babe   = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sp-keystore         = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sp-runtime          = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sp-transaction-pool = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
