[package]
name = "node-runtime"
version = "0.1.0"
authors = ["Darwinia Network <hello@itering.com>"]
edition = "2018"

[dependencies]
integer-sqrt = { version = "0.1.2" }
safe-mix = { version = "1.0", default-features = false }
parity-codec = { version = "4.1.1", default-features = false, features = ["derive"] }
substrate-primitives = { git = 'https://github.com/paritytech/substrate.git', default-features = false }
client = { package = "substrate-client", git = 'https://github.com/paritytech/substrate.git', default-features = false }
rstd = { package = "sr-std", git = 'https://github.com/paritytech/substrate.git', default-features = false }
runtime_primitives = { package = "sr-primitives",git = 'https://github.com/paritytech/substrate.git', default-features = false }
offchain-primitives = { package = "substrate-offchain-primitives", git = 'https://github.com/paritytech/substrate.git', default-features = false }
version = { package = "sr-version", git = 'https://github.com/paritytech/substrate.git', default-features = false }
support = { package = "srml-support", git = 'https://github.com/paritytech/substrate.git', default-features = false }
#aura = { package = "srml-aura", git = 'https://github.com/paritytech/substrate.git', default-features = false }
balances = { package = "srml-balances", git = 'https://github.com/paritytech/substrate.git', default-features = false }
contracts = { package = "srml-contracts", git = 'https://github.com/paritytech/substrate.git', default-features = false }
council = { package = "srml-council", git = 'https://github.com/paritytech/substrate.git', default-features = false }
democracy = { package = "srml-democracy", git = 'https://github.com/paritytech/substrate.git', default-features = false }
executive = { package = "srml-executive", git = 'https://github.com/paritytech/substrate.git', default-features = false }
authorship = { package = "srml-authorship", git = 'https://github.com/paritytech/substrate.git', default-features = false }
finality-tracker = { package = "srml-finality-tracker", git = 'https://github.com/paritytech/substrate.git', default-features = false }
grandpa = { package = "srml-grandpa", git = 'https://github.com/paritytech/substrate.git', default-features = false }
indices = { package = "srml-indices", git = 'https://github.com/paritytech/substrate.git', default-features = false }
session = { package = "srml-session", git = 'https://github.com/paritytech/substrate.git', default-features = false }
#staking-deprecated = { package = "srml-staking-deprecated", git = 'https://github.com/paritytech/substrate.git', default-features = false }
system = { package = "srml-system", git = 'https://github.com/paritytech/substrate.git', default-features = false }
timestamp = { package = "srml-timestamp", git = 'https://github.com/paritytech/substrate.git', default-features = false }
treasury = { package = "srml-treasury", git = 'https://github.com/paritytech/substrate.git', default-features = false }
sudo = { package = "srml-sudo", git = 'https://github.com/paritytech/substrate.git', default-features = false }
node-primitives = {path = "../primitives", default-features = false }
consensus_aura = { package = "substrate-consensus-aura-primitives", git = 'https://github.com/paritytech/substrate.git', default-features = false }
rustc-hex = { version = "2.0", optional = true }
serde = { version = "1.0", optional = true }
substrate-keyring = { git = 'https://github.com/paritytech/substrate.git', optional = true }
# customed
#ring = { package = "evo-ring", path = '../../srml/token/ring', default-features = false}
kton = { package = "evo-kton", path = '../../srml/kton', default-features = false}
staking = { package = "evo-staking", path = "../../srml/staking", default-features = false}
aura = { package = "srml-aura",  path = "../../srml/aura", default-features = false }
reward = { package = "evo-reward", path = "../../srml/reward", default-features = false}
gringotts = { package = "evo-gringotts", path = "../../srml/gringotts", default-features = false}

[features]
default = ["std"]
core = [
	"contracts/core",
]
std = [
	"parity-codec/std",
	"substrate-primitives/std",
	"rstd/std",
	"runtime_primitives/std",
	"support/std",
	"aura/std",
	"balances/std",
	"contracts/std",
	"council/std",
	"democracy/std",
	"executive/std",
	"finality-tracker/std",
	"grandpa/std",
	"indices/std",
	"session/std",
	"authorship/std",
	"staking/std",
	"system/std",
	"timestamp/std",
	"treasury/std",
	"sudo/std",
	"version/std",
	"node-primitives/std",
	"serde",
	"safe-mix/std",
	"client/std",
	"consensus_aura/std",
	"rustc-hex",
	"substrate-keyring",
	"offchain-primitives/std",
	"kton/std",
	"reward/std",
	"gringotts/std",
]
