[package]
name = "evo-support"
version = "0.1.0"
authors = ["hammeWang <dsw0602@foxmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
codec = { package = "parity-codec", version = "3.5.1", default-features = false, features = ["derive"] }
srml-metadata = { git = 'https://github.com/paritytech/substrate.git', default-features = false }
rstd = { package = "sr-std", git = 'https://github.com/paritytech/substrate.git', default-features = false }
runtime_io = { package = "sr-io", git = 'https://github.com/paritytech/substrate.git', default-features = false }
sr-primitives = { git = 'https://github.com/paritytech/substrate.git', default-features = false }
srml-support = { git = 'https://github.com/paritytech/substrate.git', default-features = false }


[features]
default = ["std"]
std = [
	"serde",
	"runtime_io/std",
	"codec/std",
	"sr-primitives/std",
	"srml-metadata/std",
	"srml-support/std",
	"rstd/std"
]