[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia node service"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-service"
repository  = "https://github.com/darwinia-network/darwinia/"
version     = "0.10.0"

[dependencies]
# crates
array-bytes = { version = "1.3.3" }
codec       = { package = "parity-scale-codec", version = "2.1.1", features = ["derive"] }
futures     = { version = "0.3.15" }
log         = { version = "0.4.14" }
serde       = { version = "1.0.126", features = ["derive"] }
serde_json  = { version = "1.0.64" }
# darwinia frame
darwinia-balances-rpc-runtime-api   = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "darwinia-v0.11.0" }
darwinia-header-mmr-rpc-runtime-api = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "darwinia-v0.11.0" }
darwinia-staking-rpc-runtime-api    = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "darwinia-v0.11.0" }
# dvm
darwinia-evm        = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "darwinia-v0.11.0" }
dc-db               = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "darwinia-v0.11.0" }
dc-mapping-sync     = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "darwinia-v0.11.0" }
dc-rpc              = { features = ["rpc_binary_search_estimate"], git = "https://github.com/darwinia-network/darwinia-common.git", tag = "darwinia-v0.11.0" }
dp-rpc              = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "darwinia-v0.11.0" }
dvm-rpc-runtime-api = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "darwinia-v0.11.0" }
# darwinia primitives
darwinia-primitives = { path = "../../primitives" }
# darwinia rpc
darwinia-rpc = { path = "../../rpc" }
# darwinia runtime
crab-runtime     = { path = "../../runtime/crab" }
darwinia-runtime = { path = "../../runtime/darwinia" }
# substrate client
sc-authority-discovery = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sc-basic-authorship    = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sc-chain-spec          = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sc-client-api          = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sc-client-db           = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sc-consensus           = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sc-consensus-babe      = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sc-executor            = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sc-finality-grandpa    = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sc-network             = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sc-service             = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sc-telemetry           = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sc-transaction-pool    = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
# substrate frame
frame-system-rpc-runtime-api               = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
pallet-im-online                           = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
substrate-prometheus-endpoint              = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
# substrate primitives
sc-consensus-slots     = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sc-keystore            = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sp-api                 = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sp-authority-discovery = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sp-block-builder       = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sp-blockchain          = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sp-consensus           = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sp-consensus-babe      = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sp-core                = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sp-finality-grandpa    = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sp-inherents           = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sp-offchain            = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sp-runtime             = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sp-session             = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sp-transaction-pool    = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }
sp-trie                = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.0" }

[features]
default = ["db", "full-node"]

db        = ["sc-service/db"]
full-node = []

dev = [
	"crab-runtime/dev",
	"darwinia-runtime/dev",
]

# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
try-runtime = [
	"crab-runtime/try-runtime",
	"darwinia-runtime/try-runtime",
]
