[package]
name = "evo-sdr"
version = "0.1.0"
authors = ["Evolution Land <hello@evolution.land>"]
edition = "2018"

[dependencies]
hex-literal = "0.1.0"
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
safe-mix = { version = "1.0", default-features = false}
parity-codec = { version = "3.2", default-features = false }
parity-codec-derive = { version = "3.2", default-features = false }
substrate-keyring = { git = "https://github.com/paritytech/substrate", optional = true }
sr-std = { git = "https://github.com/paritytech/substrate", default-features = false }
sr-primitives = { git = "https://github.com/paritytech/substrate", default-features = false }
srml-support = { git = "https://github.com/paritytech/substrate", default-features = false }
srml-system = { git = "https://github.com/paritytech/substrate", default-features = false }
srml-balances = { git = "https://github.com/paritytech/substrate", default_features = false }
srml-timestamp = { git = "https://github.com/paritytech/substrate", default_features = false }


[features]
default = ["std"]
std = [
    "serde/std",
    "serde_derive",
    "safe-mix/std",
    "parity-codec/std",
    "parity-codec-derive/std",
    "sr-std/std",
    "srml-support/std",
    "srml-balances/std",
    "sr-primitives/std",
    "srml-system/std",
    "srml-timestamp/std",
]
