[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
build       = "build.rs"
description = "Darwinia Client Node"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-cli"
repository  = "https://github.com/darwinia-network/darwinia/"
version     = "0.10.0"

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# crates
log                  = { version = "0.4.14" }
serde                = { version = "1.0.125", optional = true }
structopt            = { version = "0.3.21" }
tokio                = { version = "0.3.7", optional = true, features = ["rt-multi-thread"] }
# darwinia client
darwinia-cli = { optional = true, git = "https://github.com/darwinia-network/darwinia-common.git", tag = "darwinia-v0.10.0" }
# darwinia service
darwinia-service = { default-features = false, path = "../node/service" }
# substrate client
sc-cli          = { optional = true, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }
sc-client-api   = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }
sc-executor     = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }
sc-network      = { optional = true, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }
sc-service      = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }
sc-tracing      = { optional = true, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }
try-runtime-cli = { optional = true, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }
# substrate primitives
sp-core = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }
# this crate is used only to enable `trie-memory-tracker` feature
# see https://github.com/paritytech/substrate/pull/6745
sp-trie = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }
try-runtime-cli              = { optional = true, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }

[features]
default = [
	"cli",
	"db",
]

cli = [
	"serde",
	"tokio",
	"sc-cli",
	"sc-network",
	"sc-tracing",
	"darwinia-cli",
	"darwinia-service/full-node",
]
db  = ["darwinia-service/db"]

trie-memory-tracker = ["sp-trie/memory-tracker"]
wasmtime            = [
	"sc-cli/wasmtime",
	"trie-memory-tracker",
]

dev = ["darwinia-service/dev"]

try-runtime = [
	"darwinia-service/try-runtime",
	"try-runtime-cli",
]
