[package]
name = "srml-aura"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
parity-codec = { version = "3.3", default-features = false, features = ["derive"] }
serde = { version = "1.0", optional = true }
inherents = { package = "substrate-inherents", git = 'https://github.com/paritytech/substrate.git', default-features = false }
rstd = { package = "sr-std", git = 'https://github.com/paritytech/substrate.git', default-features = false }
primitives = { package = "sr-primitives", git = 'https://github.com/paritytech/substrate.git', default-features = false }
substrate-primitives = { git = 'https://github.com/paritytech/substrate.git', default-features = false }
srml-support = { git = 'https://github.com/paritytech/substrate.git', default-features = false }
system = { package = "srml-system", git = 'https://github.com/paritytech/substrate.git', default-features = false }
timestamp = { package = "srml-timestamp", git = 'https://github.com/paritytech/substrate.git', default-features = false }
staking = { package = "evo-staking", path = "../staking", default-features = false }
session = { package = "srml-session", git = 'https://github.com/paritytech/substrate.git', default-features = false }
substrate-consensus-aura-primitives = { git = 'https://github.com/paritytech/substrate.git', default-features = false}

[dev-dependencies]
lazy_static = "1.0"
parking_lot = "0.8.0"
runtime_io = { package = "sr-io", git = 'https://github.com/paritytech/substrate.git' }

[features]
default = ["std"]
std = [
	"serde",
	"parity-codec/std",
	"rstd/std",
	"srml-support/std",
	"primitives/std",
	"substrate-primitives/std",
	"system/std",
	"timestamp/std",
	"staking/std",
	"inherents/std",
	"substrate-consensus-aura-primitives/std",
]
