[package]
authors.workspace = true
description       = "Koi runtime."
edition.workspace = true
name              = "koi-runtime"
readme            = "README.md"
version.workspace = true

[build-dependencies]
# polkadot-sdk optional
substrate-wasm-builder = { workspace = true, optional = true }

[dependencies]
# crates.io
array-bytes = { workspace = true }
codec       = { workspace = true, package = "parity-scale-codec" }
log         = { workspace = true }
scale-info  = { workspace = true }
strum       = { workspace = true, features = ["derive"] }

# darwinia
darwinia-asset-limit              = { workspace = true }
darwinia-common-runtime           = { workspace = true }
darwinia-deposit                  = { workspace = true }
darwinia-ethtx-forwarder          = { workspace = true }
darwinia-precompile-assets        = { workspace = true }
darwinia-precompile-deposit       = { workspace = true }
darwinia-precompile-staking       = { workspace = true }
darwinia-precompile-state-storage = { workspace = true }
darwinia-staking                  = { workspace = true }
dc-primitives                     = { workspace = true }

# frontier
fp-evm                         = { workspace = true }
fp-rpc                         = { workspace = true }
fp-self-contained              = { workspace = true }
pallet-ethereum                = { workspace = true }
pallet-evm                     = { workspace = true }
pallet-evm-precompile-blake2   = { workspace = true }
pallet-evm-precompile-bls12381 = { workspace = true }
pallet-evm-precompile-bn128    = { workspace = true }
pallet-evm-precompile-dispatch = { workspace = true }
pallet-evm-precompile-modexp   = { workspace = true }
pallet-evm-precompile-simple   = { workspace = true }

# moonbeam
moonbeam-evm-tracer                     = { workspace = true, optional = true }
moonbeam-rpc-primitives-debug           = { workspace = true }
pallet-asset-manager                    = { workspace = true }
pallet-ethereum-xcm                     = { workspace = true }
pallet-evm-precompile-conviction-voting = { workspace = true }
precompile-utils                        = { workspace = true }
xcm-primitives                          = { workspace = true }

# open-web3-stack
orml-xcm-support = { workspace = true }
orml-xtokens     = { workspace = true }

# polkadot-sdk
cumulus-pallet-aura-ext                    = { workspace = true }
cumulus-pallet-dmp-queue                   = { workspace = true }
cumulus-pallet-parachain-system            = { workspace = true }
cumulus-pallet-xcm                         = { workspace = true }
cumulus-pallet-xcmp-queue                  = { workspace = true }
cumulus-primitives-aura                    = { workspace = true }
cumulus-primitives-core                    = { workspace = true }
cumulus-primitives-utility                 = { workspace = true }
frame-executive                            = { workspace = true }
frame-support                              = { workspace = true }
frame-system                               = { workspace = true }
frame-system-rpc-runtime-api               = { workspace = true }
pallet-assets                              = { workspace = true }
pallet-aura                                = { workspace = true }
pallet-authorship                          = { workspace = true }
pallet-balances                            = { workspace = true }
pallet-collective                          = { workspace = true }
pallet-conviction-voting                   = { workspace = true }
pallet-message-queue                       = { workspace = true }
pallet-preimage                            = { workspace = true }
pallet-proxy                               = { workspace = true }
pallet-referenda                           = { workspace = true }
pallet-scheduler                           = { workspace = true }
pallet-session                             = { workspace = true }
pallet-sudo                                = { workspace = true }
pallet-timestamp                           = { workspace = true }
pallet-transaction-payment                 = { workspace = true }
pallet-transaction-payment-rpc-runtime-api = { workspace = true }
pallet-treasury                            = { workspace = true }
pallet-tx-pause                            = { workspace = true }
pallet-utility                             = { workspace = true }
pallet-whitelist                           = { workspace = true }
pallet-xcm                                 = { workspace = true }
parachain-info                             = { workspace = true }
polkadot-parachain                         = { workspace = true }
polkadot-runtime-common                    = { workspace = true }
sp-api                                     = { workspace = true }
sp-block-builder                           = { workspace = true }
sp-consensus-aura                          = { workspace = true }
sp-core                                    = { workspace = true }
sp-debug-derive                            = { workspace = true, optional = true, features = ["force-debug"] }
sp-genesis-builder                         = { workspace = true }
sp-inherents                               = { workspace = true }
sp-offchain                                = { workspace = true }
sp-runtime                                 = { workspace = true }
sp-session                                 = { workspace = true }
sp-staking                                 = { workspace = true }
sp-std                                     = { workspace = true }
sp-transaction-pool                        = { workspace = true }
sp-version                                 = { workspace = true }
xcm                                        = { workspace = true }
xcm-builder                                = { workspace = true }
xcm-executor                               = { workspace = true }
# polkadot-sdk optional
cumulus-pallet-session-benchmarking = { workspace = true, optional = true }
frame-benchmarking                  = { workspace = true, optional = true }
frame-system-benchmarking           = { workspace = true, optional = true }
frame-try-runtime                   = { workspace = true, optional = true }

[dev-dependencies]
# darwinia
darwinia-common-runtime = { workspace = true, features = ["std", "test"] }
# polkadot-sdk
polkadot-primitives = { workspace = true, features = ["std"] }
sp-io               = { workspace = true, features = ["std"] }
sp-keyring          = { workspace = true }

[features]
default = ["std"]
std = [
	# crates.io
	"codec/std",
	"log/std",
	"scale-info/std",
	"strum/std",

	# darwinia
	"darwinia-asset-limit/std",
	"darwinia-common-runtime/std",
	"darwinia-deposit/std",
	"darwinia-ethtx-forwarder/std",
	"darwinia-precompile-assets/std",
	"darwinia-precompile-deposit/std",
	"darwinia-precompile-staking/std",
	"darwinia-precompile-state-storage/std",
	"darwinia-staking/std",
	"dc-primitives/std",

	# frontier
	"fp-evm/std",
	"fp-rpc/std",
	"fp-self-contained/std",
	"pallet-ethereum/std",
	"pallet-evm-precompile-blake2/std",
	"pallet-evm-precompile-bls12381/std",
	"pallet-evm-precompile-bn128/std",
	"pallet-evm-precompile-dispatch/std",
	"pallet-evm-precompile-modexp/std",
	"pallet-evm-precompile-simple/std",
	"pallet-evm/std",

	# moonbeam
	"moonbeam-evm-tracer/std",
	"moonbeam-rpc-primitives-debug/std",
	"pallet-asset-manager/std",
	"pallet-ethereum-xcm/std",
	"pallet-evm-precompile-conviction-voting/std",
	"precompile-utils/std",
	"xcm-primitives/std",

	# open-web3-stack
	"orml-xcm-support/std",
	"orml-xtokens/std",

	# polkadot-sdk
	"cumulus-pallet-aura-ext/std",
	"cumulus-pallet-dmp-queue/std",
	"cumulus-pallet-parachain-system/std",
	"cumulus-pallet-xcm/std",
	"cumulus-pallet-xcmp-queue/std",
	"cumulus-primitives-aura/std",
	"cumulus-primitives-core/std",
	"cumulus-primitives-utility/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"pallet-assets/std",
	"pallet-aura/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"pallet-collective/std",
	"pallet-conviction-voting/std",
	"pallet-message-queue/std",
	"pallet-preimage/std",
	"pallet-proxy/std",
	"pallet-referenda/std",
	"pallet-scheduler/std",
	"pallet-session/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"pallet-treasury/std",
	"pallet-tx-pause/std",
	"pallet-utility/std",
	"pallet-whitelist/std",
	"pallet-xcm/std",
	"parachain-info/std",
	"polkadot-parachain/std",
	"polkadot-runtime-common/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-core/std",
	"sp-debug-derive?/std",
	"sp-genesis-builder/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm/std",
	# polkadot-sdk optional
	"cumulus-pallet-session-benchmarking?/std",
	"frame-benchmarking?/std",
	"frame-system-benchmarking?/std",
	"frame-try-runtime?/std",
	"substrate-wasm-builder",
]

evm-tracing = [
	# moonbeam
	"moonbeam-evm-tracer",
]

force-debug = [
	# polkadot-sdk
	"sp-debug-derive",
]

fast-runtime = []

# A feature that should be enabled when the runtime should be build for on-chain
# deployment. This will disable stuff that shouldn't be part of the on-chain wasm
# to make it smaller like logging for example.
on-chain-release-build = [
	# polkadot-sdk
	"sp-api/disable-logging",
]

runtime-benchmarks = [
	# darwinia
	"darwinia-common-runtime/runtime-benchmarks",
	"darwinia-deposit/runtime-benchmarks",
	"darwinia-ethtx-forwarder/runtime-benchmarks",
	"darwinia-precompile-assets/runtime-benchmarks",
	"darwinia-precompile-staking/runtime-benchmarks",
	"darwinia-staking/runtime-benchmarks",

	# frontier
	"pallet-ethereum/runtime-benchmarks",
	"pallet-evm/runtime-benchmarks",

	# moonbeam
	"pallet-asset-manager/runtime-benchmarks",
	"pallet-ethereum-xcm/runtime-benchmarks",
	"xcm-primitives/runtime-benchmarks",

	# open-web3-stack
	"orml-xtokens/runtime-benchmarks",

	# polkadot-sdk
	"cumulus-pallet-parachain-system/runtime-benchmarks",
	"cumulus-pallet-xcmp-queue/runtime-benchmarks",
	"cumulus-primitives-core/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-collective/runtime-benchmarks",
	"pallet-conviction-voting/runtime-benchmarks",
	"pallet-message-queue/runtime-benchmarks",
	"pallet-preimage/runtime-benchmarks",
	"pallet-proxy/runtime-benchmarks",
	"pallet-referenda/runtime-benchmarks",
	"pallet-scheduler/runtime-benchmarks",
	"pallet-sudo/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-treasury/runtime-benchmarks",
	"pallet-tx-pause/runtime-benchmarks",
	"pallet-utility/runtime-benchmarks",
	"pallet-whitelist/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"polkadot-parachain/runtime-benchmarks",
	"polkadot-runtime-common/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
	# polkadot-sdk optional
	"cumulus-pallet-session-benchmarking/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-system-benchmarking/runtime-benchmarks",
	"sp-staking/runtime-benchmarks",
]

try-runtime = [
	# darwinia
	"darwinia-asset-limit/try-runtime",
	"darwinia-deposit/try-runtime",
	"darwinia-ethtx-forwarder/try-runtime",
	"darwinia-staking/try-runtime",

	# moonbeam
	"pallet-asset-manager/try-runtime",
	"pallet-ethereum-xcm/try-runtime",

	# open-web3-stack
	"orml-xtokens/try-runtime",

	# frontier
	"fp-self-contained/try-runtime",
	"pallet-ethereum/try-runtime",
	"pallet-evm/try-runtime",

	# polkadot-sdk
	"cumulus-pallet-aura-ext/try-runtime",
	"cumulus-pallet-dmp-queue/try-runtime",
	"cumulus-pallet-parachain-system/try-runtime",
	"cumulus-pallet-xcm/try-runtime",
	"cumulus-pallet-xcmp-queue/try-runtime",
	"frame-executive/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-assets/try-runtime",
	"pallet-aura/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-collective/try-runtime",
	"pallet-conviction-voting/try-runtime",
	"pallet-message-queue/try-runtime",
	"pallet-preimage/try-runtime",
	"pallet-proxy/try-runtime",
	"pallet-referenda/try-runtime",
	"pallet-scheduler/try-runtime",
	"pallet-session/try-runtime",
	"pallet-sudo/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"pallet-treasury/try-runtime",
	"pallet-tx-pause/try-runtime",
	"pallet-utility/try-runtime",
	"pallet-whitelist/try-runtime",
	"pallet-xcm/try-runtime",
	"parachain-info/try-runtime",
	"polkadot-runtime-common/try-runtime",
	"sp-runtime/try-runtime",
	# polkadot-sdk optional
	"frame-try-runtime/try-runtime",
]
