[package]
authors.workspace = true
description       = "Darwinia messages gadget."
edition.workspace = true
name              = "darwinia-message-gadget"
readme            = "README.md"
version.workspace = true

[dependencies]
# crates.io
codec      = { package = "parity-scale-codec", workspace = true }
scale-info = { workspace = true }

# frontier
pallet-evm = { workspace = true }

# paritytech
frame-support = { workspace = true }
frame-system  = { workspace = true }
sp-core       = { workspace = true }
sp-io         = { workspace = true }
sp-std        = { workspace = true }

[dev-dependencies]
# crates.io
array-bytes = { workspace = true }

# substrate
pallet-balances  = { workspace = true, features = ["std"] }
pallet-timestamp = { workspace = true, features = ["std"] }

[features]
default = ["std"]

std = [
	# crates.io
	"codec/std",
	"scale-info/std",

	# frontier
	"pallet-evm/std",

	# paritytech
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-io/std",
]

try-runtime = ["frame-support/try-runtime"]
