[package]
name = "node-executor"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node implementation in Rust."
edition = "2018"

[dependencies]
trie-root = "0.12"
parity-codec = "3.3"
runtime_io = { package = "sr-io", git = 'https://github.com/paritytech/substrate.git' }
state_machine = { package = "substrate-state-machine", git = 'https://github.com/paritytech/substrate.git' }
substrate-executor = { git = 'https://github.com/paritytech/substrate.git' }
primitives = { package = "substrate-primitives", git = 'https://github.com/paritytech/substrate.git' }
trie = { package = "substrate-trie", git = 'https://github.com/paritytech/substrate.git' }
node-primitives = { path = "../primitives" }
node-runtime = { path = "../runtime" }

[dev-dependencies]
test-client = { package = "substrate-test-client", git = 'https://github.com/paritytech/substrate.git' }
keyring = { package = "substrate-keyring", git = 'https://github.com/paritytech/substrate.git' }
runtime_primitives = { package = "sr-primitives", git = 'https://github.com/paritytech/substrate.git' }
runtime_support = { package = "srml-support", git = 'https://github.com/paritytech/substrate.git' }
balances = { package = "srml-balances",git = 'https://github.com/paritytech/substrate.git' }
session = { package = "srml-session", git = 'https://github.com/paritytech/substrate.git' }
staking = { package = "srml-staking", git = 'https://github.com/paritytech/substrate.git' }
system = { package = "srml-system", git = 'https://github.com/paritytech/substrate.git' }
timestamp = { package = "srml-timestamp", git = 'https://github.com/paritytech/substrate.git' }
treasury = { package = "srml-treasury", git = 'https://github.com/paritytech/substrate.git'  }
contracts = { package = "srml-contracts", git = 'https://github.com/paritytech/substrate.git' }
grandpa = { package = "srml-grandpa", git = 'https://github.com/paritytech/substrate.git' }
indices = { package = "srml-indices", git = 'https://github.com/paritytech/substrate.git' }
wabt = "~0.7.4"

[features]
benchmarks = []
