[package]
name = "try"
version = "0.1.0"
authors = ["hammeWang <dsw0602@foxmail.com>"]
edition = "2018"

[dependencies]
hex-literal = "0.2.0"
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
safe-mix = { version = "1.0", default-features = false}
parity-codec = { version = "4.1.1", default-features = false }
parity-codec-derive = { version = "3.3.0", default-features = false }
substrate-keyring = { git = "https://github.com/paritytech/substrate", optional = true }
primitives = { package = "substrate-primitives", git = "https://github.com/paritytech/substrate", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/paritytech/substrate", default-features = false }
sr-primitives = { git = "https://github.com/paritytech/substrate", default-features = false }
support = { package = "srml-support", git = "https://github.com/paritytech/substrate", default-features = false }
system = { package = "srml-system", git = "https://github.com/paritytech/substrate", default-features = false }
sr-io = { git = "https://github.com/paritytech/substrate", default-features = false }


[features]
default = ["std"]
std = [
    "serde/std",
    "serde_derive",
    "safe-mix/std",
    "parity-codec/std",
    "parity-codec-derive/std",
    "primitives/std",
    "rstd/std",
    "sr-io/std",
    "support/std",
    "sr-primitives/std",
    "system/std",
]
